

[workspace]
members = ["na-quadrature", "na-discrete-filtering",
           "book-problems/common",
           "book-problems/p13", "book-problems/p14"]

[replace]
"linxal:0.5.0" = { git = "https://github.com/DiamondLovesYou/linxal.git", branch = "merged-prs", default-features = false, features = ["openblas-static"] }