[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
name = "plot-helper"
version = "0.1.0"

[dependencies]
gnuplot = "^0.0"
ndarray = "^0.9"

[dependencies.util]
optional = false
path = "../util"
