[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
name = "na-quadrature"
version = "0.1.0"

[dependencies]
alga = "^0.5"
ndarray = "^0.9"
num-traits = "^0.1"
rand = "^0.3"

[dependencies.linxal]
version = "^0.6"
default-features = false
features = ["netlib"]
