[package]
authors = ["Richard Diamond <wichard@vitalitystudios.com>"]
name = "na-quadrature"
version = "0.1.0"

[dependencies]
alga = "0.5.1"
ndarray = "0.8.0"
num-traits = "0.1.37"
rand = "0.3.15"

[dependencies.linxal]
git = "https://github.com/DiamondLovesYou/linxal"